[project]
name = "music-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.0.2",
    "langchain-deepseek>=1.0.0",
    "python-dotenv>=1.1.1",
]
